# Generated by Django 5.1.3 on 2024-12-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_parkinglocation_latitude_parkinglocation_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateField(),
        ),
    ]
